sudo: required
services: 
  - docker

before_install:
  - docker build -t anthoney28/docker-react-basics -f Dockerfile.dev .

script:
  - docker run -e CI=true anthoney28/docker-react-basics npm run test